// Code generated by internal/gen; DO NOT EDIT.

// This file provides All2..All8: heterogeneous, fixed-arity joins that All
// cannot express because Go generics have no variadic type parameters. Each is
// the typed-tuple analogue of All, with identical fail-fast semantics. Unlike
// All, these block and return their values directly, because a promise of a
// tuple cannot be destructured on Await.

package promise

// All2 waits for 2 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All2 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All2[T1, T2 any](p1 *Promise[T1], p2 *Promise[T2]) (T1, T2, error) {
	var v1 T1
	var v2 T2
	errCh := make(chan error, 2)
	aborters := []aborter{p1, p2}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 2; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		return z1, z2, firstErr
	}
	return v1, v2, nil
}

// All3 waits for 3 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All3 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All3[T1, T2, T3 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3]) (T1, T2, T3, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	errCh := make(chan error, 3)
	aborters := []aborter{p1, p2, p3}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 3; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		return z1, z2, z3, firstErr
	}
	return v1, v2, v3, nil
}

// All4 waits for 4 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All4 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All4[T1, T2, T3, T4 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3], p4 *Promise[T4]) (T1, T2, T3, T4, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	var v4 T4
	errCh := make(chan error, 4)
	aborters := []aborter{p1, p2, p3, p4}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	go func() { var e error; v4, e = p4.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 4; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		var z4 T4
		return z1, z2, z3, z4, firstErr
	}
	return v1, v2, v3, v4, nil
}

// All5 waits for 5 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All5 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All5[T1, T2, T3, T4, T5 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3], p4 *Promise[T4], p5 *Promise[T5]) (T1, T2, T3, T4, T5, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	var v4 T4
	var v5 T5
	errCh := make(chan error, 5)
	aborters := []aborter{p1, p2, p3, p4, p5}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	go func() { var e error; v4, e = p4.Await(); errCh <- e }()
	go func() { var e error; v5, e = p5.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 5; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		var z4 T4
		var z5 T5
		return z1, z2, z3, z4, z5, firstErr
	}
	return v1, v2, v3, v4, v5, nil
}

// All6 waits for 6 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All6 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All6[T1, T2, T3, T4, T5, T6 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3], p4 *Promise[T4], p5 *Promise[T5], p6 *Promise[T6]) (T1, T2, T3, T4, T5, T6, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	var v4 T4
	var v5 T5
	var v6 T6
	errCh := make(chan error, 6)
	aborters := []aborter{p1, p2, p3, p4, p5, p6}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	go func() { var e error; v4, e = p4.Await(); errCh <- e }()
	go func() { var e error; v5, e = p5.Await(); errCh <- e }()
	go func() { var e error; v6, e = p6.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 6; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		var z4 T4
		var z5 T5
		var z6 T6
		return z1, z2, z3, z4, z5, z6, firstErr
	}
	return v1, v2, v3, v4, v5, v6, nil
}

// All7 waits for 7 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All7 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All7[T1, T2, T3, T4, T5, T6, T7 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3], p4 *Promise[T4], p5 *Promise[T5], p6 *Promise[T6], p7 *Promise[T7]) (T1, T2, T3, T4, T5, T6, T7, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	var v4 T4
	var v5 T5
	var v6 T6
	var v7 T7
	errCh := make(chan error, 7)
	aborters := []aborter{p1, p2, p3, p4, p5, p6, p7}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	go func() { var e error; v4, e = p4.Await(); errCh <- e }()
	go func() { var e error; v5, e = p5.Await(); errCh <- e }()
	go func() { var e error; v6, e = p6.Await(); errCh <- e }()
	go func() { var e error; v7, e = p7.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 7; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		var z4 T4
		var z5 T5
		var z6 T6
		var z7 T7
		return z1, z2, z3, z4, z5, z6, z7, firstErr
	}
	return v1, v2, v3, v4, v5, v6, v7, nil
}

// All8 waits for 8 promises of independent types to settle and returns
// their values as a flat tuple. It is the heterogeneous, fixed-arity analogue of
// [All]: join a known number of differently-typed promises without boxing them
// into interface{}.
//
// On the first failure, All8 aborts the sibling tasks and returns zero
// values for every result together with that error, matching All's fail-fast
// semantics.
func All8[T1, T2, T3, T4, T5, T6, T7, T8 any](p1 *Promise[T1], p2 *Promise[T2], p3 *Promise[T3], p4 *Promise[T4], p5 *Promise[T5], p6 *Promise[T6], p7 *Promise[T7], p8 *Promise[T8]) (T1, T2, T3, T4, T5, T6, T7, T8, error) {
	var v1 T1
	var v2 T2
	var v3 T3
	var v4 T4
	var v5 T5
	var v6 T6
	var v7 T7
	var v8 T8
	errCh := make(chan error, 8)
	aborters := []aborter{p1, p2, p3, p4, p5, p6, p7, p8}
	go func() { var e error; v1, e = p1.Await(); errCh <- e }()
	go func() { var e error; v2, e = p2.Await(); errCh <- e }()
	go func() { var e error; v3, e = p3.Await(); errCh <- e }()
	go func() { var e error; v4, e = p4.Await(); errCh <- e }()
	go func() { var e error; v5, e = p5.Await(); errCh <- e }()
	go func() { var e error; v6, e = p6.Await(); errCh <- e }()
	go func() { var e error; v7, e = p7.Await(); errCh <- e }()
	go func() { var e error; v8, e = p8.Await(); errCh <- e }()
	var firstErr error
	for i := 0; i < 8; i++ {
		if e := <-errCh; e != nil && firstErr == nil {
			firstErr = e
			for _, a := range aborters {
				a.Abort()
			}
		}
	}
	if firstErr != nil {
		var z1 T1
		var z2 T2
		var z3 T3
		var z4 T4
		var z5 T5
		var z6 T6
		var z7 T7
		var z8 T8
		return z1, z2, z3, z4, z5, z6, z7, z8, firstErr
	}
	return v1, v2, v3, v4, v5, v6, v7, v8, nil
}
